/*-
 * #%L
 * Software for the reconstruction of multi-view microscopic acquisitions
 * like Selective Plane Illumination Microscopy (SPIM) Data.
 * %%
 * Copyright (C) 2012 - 2025 Multiview Reconstruction developers.
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/gpl-2.0.html>.
 * #L%
 */
package net.preibisch.mvrecon.fiji.spimdata.actionhistory;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Predicate;
import java.util.regex.Pattern;

/**
 * Renders an {@link ActionRecord} as one or more BigStitcher-Spark CLI command lines.
 *
 * <p>Translation is decoupled from XML persistence: history stored in the SpimData XML
 * uses neutral param keys (e.g. {@code "label"}, {@code "method"}) and this class maps
 * those to current Spark CLI flag names. If the Spark CLI changes, only this class
 * needs to be updated; stored XMLs remain readable.</p>
 *
 * <p>The wrapper script names emitted here ({@code detect-interestpoints},
 * {@code match-interestpoints}, {@code solver}, {@code stitching}, {@code fusion},
 * {@code resave}) match the per-command shell shims generated by the BigStitcher-Spark
 * {@code install} script.</p>
 */
public class ActionToSparkCli
{
	/**
	 * A reusable bundle of key→flag pairs (and, optionally, which of them are repeatable — see
	 * {@code Recipe.repeatKeys}) mirroring a shared BigStitcher-Spark abstract command class. Recipes
	 * for Spark commands that extend the same abstract class (e.g. {@code AbstractSelectableViews})
	 * compose in the same group instead of each re-listing the same pairs by hand — the actual
	 * failure mode that motivated this: adding a shared flag meant remembering to update every
	 * recipe (and its {@code repeatKeys}) that used it.
	 */
	private static final class FlagGroup
	{
		final String[][] pairs;
		final String[] repeatableKeys;

		FlagGroup( final String[] repeatableKeys, final String[]... pairs )
		{
			this.pairs = pairs;
			this.repeatableKeys = repeatableKeys;
		}
	}

	/**
	 * {@code AbstractSelectableViews}: --angleId/--tileId/--illuminationId/--channelId/--timepointId
	 * (CSV id lists) and -vi (explicit "tp,vs" fallback, repeatable). Shared by detect-interestpoints,
	 * match-interestpoints, and solver — see {@code ActionHistoryRecorder.putViewSelection}.
	 */
	private static final FlagGroup SELECTABLE_VIEWS = new FlagGroup(
			new String[]{ "viewIds" },
			new String[]{ "angleId", "--angleId" },
			new String[]{ "tileId", "--tileId" },
			new String[]{ "illuminationId", "--illuminationId" },
			new String[]{ "channelId", "--channelId" },
			new String[]{ "timepointId", "--timepointId" },
			new String[]{ "viewIds", "-vi" }
	);

	/**
	 * {@code AbstractRegistration}'s grouping flags (on top of {@link #SELECTABLE_VIEWS}, which it
	 * also extends). Shared by match-interestpoints and solver.
	 */
	private static final FlagGroup REGISTRATION_GROUPING = new FlagGroup(
			null,
			new String[]{ "groupTiles", "--groupTiles" },
			new String[]{ "groupIllums", "--groupIllums" },
			new String[]{ "groupChannels", "--groupChannels" },
			new String[]{ "splitTimepoints", "--splitTimepoints" }
	);

	/**
	 * N5/Zarr/HDF5 output-container basics shared by every Spark command that writes one via the
	 * N5-API machinery: create-fusion-container, nonrigid-fusion, and resave. NOT shared by "fusion"
	 * (the second fusion phase reads an already-created container's metadata, it doesn't create one).
	 *
	 * <p>{@code blockScale} is deliberately NOT included here: create-fusion-container maps it to
	 * the relative {@code --shardSizeFactor} while nonrigid-fusion/resave/fusion map it to the
	 * absolute {@code --blockScale} — same recorded key, genuinely different flag semantics, so
	 * grouping it here would silently emit the wrong flag for create-fusion-container.</p>
	 */
	private static final FlagGroup N5_OUTPUT_CONTAINER = new FlagGroup(
			null,
			new String[]{ "n5Path", "-o" },
			new String[]{ "storage", "-s" },
			new String[]{ "blockSize", "--blockSize" },
			new String[]{ "useSharding", "--useSharding" }
	);

	/**
	 * N5 compression flags shared by create-fusion-container and resave. NOT shared by
	 * nonrigid-fusion, which hardcodes {@code ZstandardCompression(3)} with no CLI flag at all (see
	 * the comment on {@code nonRigidRun} below).
	 */
	private static final FlagGroup COMPRESSION = new FlagGroup(
			null,
			new String[]{ "compression", "-c" },
			new String[]{ "compressionLevel", "-cl" }
	);

	/** A single Spark command's name and the neutral-key → CLI-flag mapping. */
	private static final class Recipe
	{
		final String script;
		/** ordered: stable output across runs */
		final LinkedHashMap<String,String> keyToFlag;
		final boolean includeXml;
		/**
		 * If non-null, {@code -x} is taken from this recorded param key instead of the live project
		 * path. Used for resave, whose {@code -x} is the original input XML (captured at record time),
		 * not the currently open project (which is the resave's output).
		 */
		String xmlParamKey = null;
		/**
		 * Suppress this key's flag when {@link #suppressWhen} evaluates true against the recorded
		 * params. Used for the single case of {@code --blockScale} being rejected by SparkFusion
		 * once the container is sharded.
		 */
		String suppressKey = null;
		Predicate<Map<String,String>> suppressWhen = null;
		/**
		 * Whole-recipe gate on the affine-vs-nonrigid fusion branch: {@code null} = always apply,
		 * {@code true} = only when {@code nonRigid=true} was recorded, {@code false} = only when not.
		 */
		Boolean requiresNonRigid = null;
		/**
		 * Keys whose recorded value is a {@value #MULTI_VALUE_DELIM}-delimited list expanded into
		 * repeated flag occurrences (e.g. {@code -ip beads -ip nuclei}, {@code -fv '0,0' -fv '0,1'}).
		 */
		Set<String> repeatKeys = null;
		/**
		 * Whole-recipe skip condition evaluated against the recorded params; {@code null} = never
		 * skip. Used for stages the mvrecon GUI can run without their sibling stage, e.g. "solver" is
		 * skipped when {@code globalOptMethod=NO_OPTIMIZATION} (not a valid Spark --method value —
		 * there is no "don't solve" mode) and "match-interestpoints" is skipped when
		 * {@code skipMatching=true} (LoadCorrespondencesGUI reused existing correspondences, so
		 * there is nothing new to match).
		 */
		Predicate<Map<String,String>> skipWhen = null;

		Recipe( final String script, final boolean includeXml, final String[]... keyFlagPairs )
		{
			this( script, includeXml, new FlagGroup[0], keyFlagPairs );
		}

		/** Composes shared {@link FlagGroup}s (e.g. {@link #SELECTABLE_VIEWS}) in before the recipe's own pairs. */
		Recipe( final String script, final boolean includeXml, final FlagGroup[] groups, final String[]... keyFlagPairs )
		{
			this.script = script;
			this.includeXml = includeXml;
			this.keyToFlag = new LinkedHashMap<>();
			for ( final FlagGroup g : groups )
			{
				for ( final String[] kv : g.pairs )
					keyToFlag.put( kv[ 0 ], kv[ 1 ] );
				if ( g.repeatableKeys != null )
				{
					if ( repeatKeys == null )
						repeatKeys = new HashSet<>();
					repeatKeys.addAll( Arrays.asList( g.repeatableKeys ) );
				}
			}
			for ( final String[] kv : keyFlagPairs )
				keyToFlag.put( kv[ 0 ], kv[ 1 ] );
		}
	}

	/** Delimiter for multi-valued recorded params expanded into repeated flags (see {@code Recipe.repeatKeys}). */
	public static final String MULTI_VALUE_DELIM = ";";

	private static final Map<String,List<Recipe>> REGISTRY = buildRegistry();

	private static Map<String,List<Recipe>> buildRegistry()
	{
		final Map<String,List<Recipe>> r = new LinkedHashMap<>();

		final Recipe detectRecipe = new Recipe(
				"detect-interestpoints", true,
				new FlagGroup[]{ SELECTABLE_VIEWS },
				new String[]{ "label", "-l" },
				new String[]{ "sigma", "-s" },
				new String[]{ "threshold", "-t" },
				new String[]{ "type", "--type" },
				new String[]{ "localization", "--localization" },
				new String[]{ "minIntensity", "-i0" },
				new String[]{ "maxIntensity", "-i1" },
				new String[]{ "downsampleXY", "-dsxy" },
				new String[]{ "downsampleZ", "-dsz" },
				new String[]{ "overlappingOnly", "--overlappingOnly" },
				new String[]{ "blockSize", "--blockSize" },
				new String[]{ "medianFilter", "--medianFilter" },
				new String[]{ "maxSpots", "--maxSpots" }
		);
		r.put( "detect-interestpoints", Collections.singletonList( detectRecipe ) );

		// registration in the mvrecon GUI is two Spark stages: descriptor matching + global solve.
		// Either can run without the other: LoadCorrespondencesGUI reuses existing correspondences
		// and skips matching (emit "solver" only), and GlobalOptType.NO_OPTIMIZATION skips the solve
		// (emit "match-interestpoints" only — NO_OPTIMIZATION isn't a valid Solver --method value).
		final List<Recipe> registration = new ArrayList<>();
		final Recipe matchRecipe = new Recipe(
				"match-interestpoints", true,
				// SparkGeometricDescriptorMatching extends AbstractRegistration extends
				// AbstractSelectableViews, so it gets both shared groups
				new FlagGroup[]{ SELECTABLE_VIEWS, REGISTRATION_GROUPING },
				new String[]{ "label", "-l" },
				new String[]{ "matchingMethod", "-m" },
				new String[]{ "registrationType", "-rtp" },
				new String[]{ "referenceTP", "--referenceTP" },
				new String[]{ "rangeTP", "--rangeTP" },
				new String[]{ "transformationModel", "-tm" },
				new String[]{ "regularizationModel", "-rm" },
				new String[]{ "lambda", "--lambda" },
				new String[]{ "redundancy", "-r" },
				new String[]{ "significance", "-s" },
				new String[]{ "numNeighbors", "-n" },
				new String[]{ "searchRadius", "-sr" },
				new String[]{ "overlapType", "-vr" },
				new String[]{ "interestpointsForReg", "-ipfr" },
				new String[]{ "matchAcrossLabels", "--matchAcrossLabels" },
				new String[]{ "interestPointMergeDistance", "--interestPointMergeDistance" },
				new String[]{ "ransacIterations", "-rit" },
				new String[]{ "ransacMaxError", "-rme" },
				new String[]{ "ransacMinInlierRatio", "-rmir" },
				new String[]{ "ransacMinNumInliers", "-rmni" },
				new String[]{ "ransacMultiConsensus", "-rmc" },
				new String[]{ "icpMaxError", "-ime" },
				new String[]{ "icpIterations", "-iit" },
				new String[]{ "icpUseRANSAC", "--icpUseRANSAC" },
				new String[]{ "clearCorrespondences", "--clearCorrespondences" }
		);
		matchRecipe.skipWhen = p -> "true".equalsIgnoreCase( p.get( "skipMatching" ) );
		registration.add( matchRecipe );
		final Recipe solverRecipe = new Recipe(
				"solver", true,
				// Solver extends AbstractRegistration extends AbstractSelectableViews, same as match
				new FlagGroup[]{ SELECTABLE_VIEWS, REGISTRATION_GROUPING },
				new String[]{ "sourcePoints", "-s" },
				new String[]{ "label", "-l" },
				new String[]{ "registrationType", "-rtp" },
				new String[]{ "referenceTP", "--referenceTP" },
				new String[]{ "rangeTP", "--rangeTP" },
				new String[]{ "globalOptMethod", "--method" },
				new String[]{ "transformationModel", "-tm" },
				new String[]{ "regularizationModel", "-rm" },
				new String[]{ "lambda", "--lambda" },
				new String[]{ "preAlign", "-pa" },
				new String[]{ "relativeThreshold", "--relativeThreshold" },
				new String[]{ "absoluteThreshold", "--absoluteThreshold" },
				new String[]{ "maxError", "--maxError" },
				new String[]{ "maxIterations", "--maxIterations" },
				new String[]{ "maxPlateauwidth", "--maxPlateauwidth" },
				new String[]{ "fixedViews", "-fv" },
				new String[]{ "disableFixedViews", "--disableFixedViews" }
		);
		solverRecipe.skipWhen = p -> "NO_OPTIMIZATION".equals( p.get( "globalOptMethod" ) );
		// -fv is also repeatable ('0,0' '0,1' ...); "viewIds" is already in repeatKeys via SELECTABLE_VIEWS
		solverRecipe.repeatKeys.add( "fixedViews" );
		registration.add( solverRecipe );
		r.put( "register-interestpoints", registration );

		r.put( "pairwise-stitching", Collections.singletonList( new Recipe(
				"stitching", true,
				new String[]{ "downsampling", "-ds" },
				new String[]{ "peaksToCheck", "-p" },
				new String[]{ "minR", "--minR" },
				new String[]{ "maxR", "--maxR" },
				new String[]{ "maxShiftX", "--maxShiftX" },
				new String[]{ "maxShiftY", "--maxShiftY" },
				new String[]{ "maxShiftZ", "--maxShiftZ" },
				new String[]{ "maxShiftTotal", "--maxShiftTotal" },
				new String[]{ "channelCombine", "--channelCombine" },
				new String[]{ "illumCombine", "--illumCombine" },
				new String[]{ "disableSubpixelResolution", "--disableSubpixelResolution" }
		) ) );

		// Spark affine fusion is a two-phase workflow: create-fusion-container first (driver-only,
		// uses -x), then fusion (distributed, reads container metadata, no -x). The TPS nonrigid
		// path is a single-shot nonrigid-fusion that creates its own writer/dataset
		// (see SparkNonRigidFusion.java:237,242) and does not consume a pre-created container, so
		// create-fusion-container is skipped on that branch.
		final List<Recipe> fusion = new ArrayList<>();
		final Recipe createContainer = new Recipe(
				"create-fusion-container", true,
				new FlagGroup[]{ N5_OUTPUT_CONTAINER, COMPRESSION },
				new String[]{ "pixelType", "-d" },
				new String[]{ "minIntensity", "--minIntensity" },
				new String[]{ "maxIntensity", "--maxIntensity" },
				new String[]{ "boundingBox", "-b" },
				// explicit pyramid (-ds, split=";") supersedes --multiRes; the GUI always records an
				// explicit pyramid when multi-resolution is on, so --multiRes is intentionally omitted
				new String[]{ "downsampling", "-ds" },
				new String[]{ "preserveAnisotropy", "--preserveAnisotropy" },
				new String[]{ "anisotropyFactor", "--anisotropyFactor" },
				// CreateFusionContainer's shard size is blockSize * shardSizeFactor (a relative
				// factor), which is exactly what mvrecon's "blockScale" already means (see
				// ExportN5Api: shardSize = blockSize * blockScale) — same value, different flag name.
				// NOT part of N5_OUTPUT_CONTAINER: the other recipes sharing that group map
				// "blockScale" to the absolute "--blockScale" instead (see N5_OUTPUT_CONTAINER's doc).
				new String[]{ "blockScale", "--shardSizeFactor" },
				new String[]{ "bdv", "--bdv" },
				new String[]{ "xmlOut", "-xo" }
		);
		createContainer.requiresNonRigid = false;
		fusion.add( createContainer );
		// fusionMethod/overlapExpansion (-fm/-oe) are intentionally NOT recorded by the mvrecon GUI:
		// FusionMethod.THIN_PLATE_SPLINE is a split-dataset (oct-tree) capability
		// (BlkThinPlateSplineFusion) that Image_Fusion/ExportN5Api never wires up today, so this
		// path can only ever run as Spark's default AFFINE. Revisit once the GUI can drive TPS here
		// (distinct from the "nonrigid-fusion" interest-point-based TPS below).
		final Recipe fusionRun = new Recipe(
				"fusion", false, // fusion uses container metadata, not -x
				new String[]{ "n5Path", "-o" },
				new String[]{ "storage", "-s" },
				new String[]{ "fusion", "-f" },
				new String[]{ "fusionMethod", "-fm" },
				new String[]{ "overlapExpansion", "-oe" },
				new String[]{ "blockScale", "--blockScale" },
				new String[]{ "channelId", "--channelId" },
				new String[]{ "timepointId", "--timepointId" }
		);
		// SparkFusion rejects --blockScale once the container is sharded; shard size determines
		// the compute-block size. Omit it whenever the create-fusion-container step would shard.
		fusionRun.suppressKey = "blockScale";
		fusionRun.suppressWhen = ActionToSparkCli::shardingEnabled;
		fusionRun.requiresNonRigid = false;
		fusion.add( fusionRun );

		// Single-shot nonrigid (TPS) fusion: takes -x, writes its own dataset, requires -ip.
		// SparkNonRigidFusion validates exactly-one-of -d / --bdv. The GUI records `bdvFirst` as
		// the (tp,vs) the first fusion group would receive — only meaningful in BDV mode, and only
		// the first group (no fan-out today, see ExportN5Api.firstAssignedViewId). If the GUI ran
		// without BDV, `bdvFirst` is absent and the recorded command will need `-d <path>` filled
		// in by hand before it runs.
		// NOTE: SparkNonRigidFusion does not accept -c / -cl (compression, compressionLevel) — it
		// hardcodes ZstandardCompression(3) with no CLI flag — so those keys are recorded by the
		// GUI exporter but intentionally not mapped here. --multiRes is also omitted: the GUI always
		// records an explicit "-ds" pyramid when multi-resolution is on (same convention as
		// create-fusion-container above), so --multiRes would be redundant.
		final Recipe nonRigidRun = new Recipe(
				"nonrigid-fusion", true,
				new FlagGroup[]{ N5_OUTPUT_CONTAINER },
				new String[]{ "blockScale", "--blockScale" },
				new String[]{ "pixelType", "-p" },
				new String[]{ "minIntensity", "--minIntensity" },
				new String[]{ "maxIntensity", "--maxIntensity" },
				new String[]{ "boundingBox", "-b" },
				new String[]{ "bdvFirst", "--bdv" },
				new String[]{ "xmlOut", "-xo" },
				new String[]{ "n5Dataset", "-d" },
				new String[]{ "interestPoints", "-ip" },
				new String[]{ "preserveAnisotropy", "--preserveAnisotropy" },
				new String[]{ "anisotropyFactor", "--anisotropyFactor" },
				new String[]{ "downsampling", "-ds" },
				new String[]{ "shardSize", "--shardSize" }
		);
		nonRigidRun.requiresNonRigid = true;
		nonRigidRun.repeatKeys = Collections.singleton( "interestPoints" );
		fusion.add( nonRigidRun );
		r.put( "fusion", fusion );

		// intensity-adjustment is intentionally NOT registered: its Spark equivalent is a two-stage
		// workflow (SparkIntensityMatching + IntensitySolver) over an N5 coefficient container, which
		// has no faithful single-action mapping from the mvrecon GUI (coefficients live in the XML).

		r.put( "icp-refine", Collections.singletonList( new Recipe(
				"match-interestpoints", true,
				new String[]{ "label", "-l" },
				new String[]{ "matchingMethod", "-m" }, // expected to be "ICP"
				new String[]{ "icpMaxError", "-ime" },
				new String[]{ "icpIterations", "-iit" },
				new String[]{ "icpUseRANSAC", "--icpUseRANSAC" }
		) ) );

		// resave's -x is the original INPUT xml (recorded as "inputXml"), not the live project,
		// which after a resave is the OUTPUT. -xo (output xml) is only recorded for formats that
		// actually write a separate xml; for Zarr v3 the metadata embeds into the -o container, so
		// "xmlOut" is absent and -xo is omitted.
		final Recipe resave = new Recipe(
				"resave", true,
				new FlagGroup[]{ N5_OUTPUT_CONTAINER, COMPRESSION },
				new String[]{ "xmlOut", "-xo" },
				new String[]{ "blockScale", "--blockScale" },
				new String[]{ "downsampling", "-ds" }
		);
		resave.xmlParamKey = "inputXml";
		r.put( "resave", Collections.singletonList( resave ) );

		return r;
	}

	/**
	 * Render the action as zero-or-more Spark CLI command lines.
	 *
	 * @param record the action to translate
	 * @param xmlPath the project XML/URI to substitute into {@code -x}; may be null
	 * @return one or more lines; for unknown action ids a single comment line is returned
	 */
	public static List<String> render( final ActionRecord record, final String xmlPath )
	{
		if ( record == null )
			return Collections.emptyList();
		final List<Recipe> recipes = REGISTRY.get( record.getActionId() );
		if ( recipes == null )
			return Collections.singletonList( "# unknown action: " + record.getActionId() );

		final ArrayList<String> out = new ArrayList<>( recipes.size() );
		final Map<String,String> params = record.getParams();
		final boolean nonRigid = nonRigid( params );

		// "Around median"/"Weakest" detection limits have no Spark CLI equivalent (--maxSpots only
		// supports brightest-N, see the "maxSpots" mapping in the detect-interestpoints recipe) and
		// are silently omitted from the rendered command below; warn so that difference is visible
		// here instead of only in the raw params dump.
		final String limitMode = params.get( "limitDetectionsMode" );
		if ( limitMode != null && !"BRIGHTEST".equals( limitMode ) )
			out.add( "# WARNING: mvrecon limited detections to " + params.get( "maxDetections" ) + " (" + limitMode
					+ ") — BigStitcher-Spark's --maxSpots only supports brightest-N, so this limit is NOT applied below; results will include ALL detections." );

		// mvrecon's "match Z resolution" auto XY-downsampling resolved to different factors across
		// the processed views (mixed voxel calibration) -- -dsxy takes one value for the whole job,
		// so no single flag can represent it; the recipe below has no "downsampleXY" key to emit.
		final String dsxyVaries = params.get( "downsampleXYVaries" );
		if ( dsxyVaries != null )
			out.add( "# WARNING: mvrecon's auto XY-downsampling ('match Z resolution') resolved to different "
					+ "factors across the processed views " + dsxyVaries + " — BigStitcher-Spark's -dsxy takes "
					+ "one value for the whole job; pick one manually (or split into per-calibration runs) "
					+ "before running the command below." );

		for ( final Recipe recipe : recipes )
		{
			if ( recipe.requiresNonRigid != null && recipe.requiresNonRigid != nonRigid )
				continue;
			if ( recipe.skipWhen != null && recipe.skipWhen.test( params ) )
				continue;
			out.add( renderOne( recipe, params, xmlPath ) );
		}
		return out;
	}

	private static String renderOne( final Recipe recipe, final Map<String,String> params, final String xmlPath )
	{
		final StringBuilder sb = new StringBuilder();
		// emitted with a `./` prefix so it matches the install-script wrapper invocation convention
		sb.append( "./" ).append( recipe.script );
		if ( recipe.includeXml )
		{
			final String x = recipe.xmlParamKey != null ? params.get( recipe.xmlParamKey ) : xmlPath;
			if ( x != null && !x.isEmpty() )
				sb.append( " -x " ).append( quote( x ) );
		}

		for ( final Map.Entry<String,String> mapping : recipe.keyToFlag.entrySet() )
		{
			final String value = params.get( mapping.getKey() );
			if ( value == null || value.isEmpty() )
				continue;
			if ( mapping.getKey().equals( recipe.suppressKey ) && recipe.suppressWhen.test( params ) )
				continue;
			final String flag = mapping.getValue();
			// multi-valued: emit `flag value` per non-empty element
			if ( recipe.repeatKeys != null && recipe.repeatKeys.contains( mapping.getKey() ) )
			{
				for ( final String part : value.split( Pattern.quote( MULTI_VALUE_DELIM ) ) )
					if ( !part.isEmpty() )
						sb.append( ' ' ).append( flag ).append( ' ' ).append( quote( part ) );
				continue;
			}
			// boolean flag (value "true"): emit just the flag; "false": omit entirely
			if ( "true".equalsIgnoreCase( value ) )
				sb.append( ' ' ).append( flag );
			else if ( "false".equalsIgnoreCase( value ) )
				continue;
			else
				sb.append( ' ' ).append( flag ).append( ' ' ).append( quote( value ) );
		}
		return sb.toString();
	}

	/**
	 * Mirrors CreateFusionContainer's sharding decision: sharding is on when explicitly enabled,
	 * or when left to auto-detect (param absent) and the storage is ZARR v3. ZARR2/N5/HDF5 never
	 * shard. Storage absent defaults to ZARR v3, matching the CLI default.
	 */
	private static boolean shardingEnabled( final Map<String,String> params )
	{
		final String useSharding = params.get( "useSharding" );
		if ( "true".equalsIgnoreCase( useSharding ) )
			return true;
		if ( "false".equalsIgnoreCase( useSharding ) )
			return false;
		final String storage = params.get( "storage" );
		return storage == null || storage.isEmpty() || "ZARR".equalsIgnoreCase( storage );
	}

	/** True when the recorded fusion action ran the TPS nonrigid pathway (labels selected in GUI). */
	private static boolean nonRigid( final Map<String,String> params )
	{
		return "true".equalsIgnoreCase( params.get( "nonRigid" ) );
	}

	private static String quote( final String s )
	{
		if ( s == null )
			return "''";
		// quote if it contains shell-significant chars; otherwise leave bare
		for ( int i = 0; i < s.length(); i++ )
		{
			final char c = s.charAt( i );
			if ( c == ' ' || c == '\t' || c == '\'' || c == '"' || c == '$' || c == '\\' || c == '*' || c == '?' || c == '(' || c == ')' || c == '[' || c == ']' || c == '<' || c == '>' || c == '|' || c == '&' || c == ';' )
			{
				return "'" + s.replace( "'", "'\\''" ) + "'";
			}
		}
		return s;
	}

	/** True if the translator has a recipe for this action id. */
	public static boolean isKnown( final String actionId )
	{
		return REGISTRY.containsKey( actionId );
	}
}
