/*-
 * #%L
 * Software for the reconstruction of multi-view microscopic acquisitions
 * like Selective Plane Illumination Microscopy (SPIM) Data.
 * %%
 * Copyright (C) 2012 - 2025 Multiview Reconstruction developers.
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/gpl-2.0.html>.
 * #L%
 */
package net.preibisch.mvrecon.fiji.spimdata.actionhistory;

import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Renders an {@link ActionRecord} as one or more BigStitcher-Spark CLI command lines.
 *
 * <p>Translation is decoupled from XML persistence: history stored in the SpimData XML
 * uses neutral param keys (e.g. {@code "label"}, {@code "method"}) and this class maps
 * those to current Spark CLI flag names. If the Spark CLI changes, only this class
 * needs to be updated; stored XMLs remain readable.</p>
 *
 * <p>The wrapper script names emitted here ({@code detect-interestpoints},
 * {@code match-interestpoints}, {@code solver}, {@code stitching}, {@code fusion},
 * {@code resave}) match the per-command shell shims generated by the BigStitcher-Spark
 * {@code install} script.</p>
 */
public class ActionToSparkCli
{
	/** A single Spark command's name and the neutral-key → CLI-flag mapping. */
	private static final class Recipe
	{
		final String script;
		/** ordered: stable output across runs */
		final LinkedHashMap<String,String> keyToFlag;
		final boolean includeXml;
		/**
		 * If non-null, {@code -x} is taken from this recorded param key instead of the live project
		 * path. Used for resave, whose {@code -x} is the original input XML (captured at record time),
		 * not the currently open project (which is the resave's output).
		 */
		String xmlParamKey = null;

		Recipe( final String script, final boolean includeXml, final String[]... keyFlagPairs )
		{
			this.script = script;
			this.includeXml = includeXml;
			this.keyToFlag = new LinkedHashMap<>();
			for ( final String[] kv : keyFlagPairs )
				keyToFlag.put( kv[ 0 ], kv[ 1 ] );
		}
	}

	private static final Map<String,List<Recipe>> REGISTRY = buildRegistry();

	private static Map<String,List<Recipe>> buildRegistry()
	{
		final Map<String,List<Recipe>> r = new LinkedHashMap<>();

		r.put( "detect-interestpoints", Collections.singletonList( new Recipe(
				"detect-interestpoints", true,
				new String[]{ "label", "-l" },
				new String[]{ "sigma", "-s" },
				new String[]{ "threshold", "-t" },
				new String[]{ "type", "--type" },
				new String[]{ "localization", "--localization" },
				new String[]{ "minIntensity", "-i0" },
				new String[]{ "maxIntensity", "-i1" },
				new String[]{ "downsampleXY", "-dsxy" },
				new String[]{ "downsampleZ", "-dsz" },
				new String[]{ "overlappingOnly", "--overlappingOnly" },
				new String[]{ "blockSize", "--blockSize" },
				new String[]{ "medianFilter", "--medianFilter" },
				new String[]{ "maxSpots", "--maxSpots" }
		) ) );

		// registration in the mvrecon GUI is two Spark stages: descriptor matching + global solve
		final List<Recipe> registration = new ArrayList<>();
		registration.add( new Recipe(
				"match-interestpoints", true,
				new String[]{ "label", "-l" },
				new String[]{ "matchingMethod", "-m" },
				new String[]{ "registrationType", "-rtp" },
				new String[]{ "referenceTP", "--referenceTP" },
				new String[]{ "rangeTP", "--rangeTP" },
				new String[]{ "transformationModel", "-tm" },
				new String[]{ "regularizationModel", "-rm" },
				new String[]{ "lambda", "--lambda" },
				new String[]{ "redundancy", "-r" },
				new String[]{ "significance", "-s" },
				new String[]{ "numNeighbors", "-n" },
				new String[]{ "searchRadius", "-sr" },
				new String[]{ "overlapType", "-vr" },
				new String[]{ "interestpointsForReg", "-ipfr" },
				new String[]{ "matchAcrossLabels", "--matchAcrossLabels" },
				new String[]{ "interestPointMergeDistance", "--interestPointMergeDistance" },
				new String[]{ "ransacIterations", "-rit" },
				new String[]{ "ransacMaxError", "-rme" },
				new String[]{ "ransacMinInlierRatio", "-rmir" },
				new String[]{ "ransacMinNumInliers", "-rmni" },
				new String[]{ "ransacMultiConsensus", "-rmc" },
				new String[]{ "icpMaxError", "-ime" },
				new String[]{ "icpIterations", "-iit" },
				new String[]{ "icpUseRANSAC", "--icpUseRANSAC" },
				new String[]{ "groupTiles", "--groupTiles" },
				new String[]{ "groupIllums", "--groupIllums" },
				new String[]{ "groupChannels", "--groupChannels" },
				new String[]{ "splitTimepoints", "--splitTimepoints" },
				new String[]{ "clearCorrespondences", "--clearCorrespondences" }
		) );
		registration.add( new Recipe(
				"solver", true,
				new String[]{ "sourcePoints", "-s" },
				new String[]{ "label", "-l" },
				new String[]{ "registrationType", "-rtp" },
				new String[]{ "referenceTP", "--referenceTP" },
				new String[]{ "rangeTP", "--rangeTP" },
				new String[]{ "globalOptMethod", "--method" },
				new String[]{ "transformationModel", "-tm" },
				new String[]{ "regularizationModel", "-rm" },
				new String[]{ "lambda", "--lambda" },
				new String[]{ "preAlign", "-pa" },
				new String[]{ "relativeThreshold", "--relativeThreshold" },
				new String[]{ "absoluteThreshold", "--absoluteThreshold" },
				new String[]{ "maxError", "--maxError" },
				new String[]{ "maxIterations", "--maxIterations" },
				new String[]{ "maxPlateauwidth", "--maxPlateauwidth" },
				new String[]{ "fixedViews", "-fv" },
				new String[]{ "disableFixedViews", "--disableFixedViews" },
				new String[]{ "groupTiles", "--groupTiles" },
				new String[]{ "groupIllums", "--groupIllums" },
				new String[]{ "groupChannels", "--groupChannels" },
				new String[]{ "splitTimepoints", "--splitTimepoints" }
		) );
		r.put( "register-interestpoints", registration );

		r.put( "pairwise-stitching", Collections.singletonList( new Recipe(
				"stitching", true,
				new String[]{ "downsampling", "-ds" },
				new String[]{ "peaksToCheck", "-p" },
				new String[]{ "minR", "--minR" },
				new String[]{ "maxR", "--maxR" },
				new String[]{ "maxShiftX", "--maxShiftX" },
				new String[]{ "maxShiftY", "--maxShiftY" },
				new String[]{ "maxShiftZ", "--maxShiftZ" },
				new String[]{ "maxShiftTotal", "--maxShiftTotal" },
				new String[]{ "channelCombine", "--channelCombine" },
				new String[]{ "illumCombine", "--illumCombine" },
				new String[]{ "disableSubpixelResolution", "--disableSubpixelResolution" }
		) ) );

		// Spark fusion is a two-phase workflow: create-fusion-container first (driver-only,
		// uses -x), then fusion (distributed, reads container metadata, no -x).
		final List<Recipe> fusion = new ArrayList<>();
		fusion.add( new Recipe(
				"create-fusion-container", true,
				new String[]{ "n5Path", "-o" },
				new String[]{ "storage", "-s" },
				new String[]{ "compression", "-c" },
				new String[]{ "compressionLevel", "-cl" },
				new String[]{ "pixelType", "-d" },
				new String[]{ "blockSize", "--blockSize" },
				new String[]{ "minIntensity", "--minIntensity" },
				new String[]{ "maxIntensity", "--maxIntensity" },
				new String[]{ "boundingBox", "-b" },
				// explicit pyramid (-ds, split=";") supersedes --multiRes; the GUI always records an
				// explicit pyramid when multi-resolution is on, so --multiRes is intentionally omitted
				new String[]{ "downsampling", "-ds" },
				new String[]{ "preserveAnisotropy", "--preserveAnisotropy" },
				new String[]{ "anisotropyFactor", "--anisotropyFactor" },
				new String[]{ "useSharding", "--useSharding" },
				new String[]{ "bdv", "--bdv" },
				new String[]{ "xmlOut", "-xo" }
		) );
		fusion.add( new Recipe(
				"fusion", false, // fusion uses container metadata, not -x
				new String[]{ "n5Path", "-o" },
				new String[]{ "storage", "-s" },
				new String[]{ "fusion", "-f" },
				new String[]{ "fusionMethod", "-fm" },
				new String[]{ "overlapExpansion", "-oe" },
				new String[]{ "blockScale", "--blockScale" },
				new String[]{ "channelId", "--channelId" },
				new String[]{ "timepointId", "--timepointId" }
		) );
		r.put( "fusion", fusion );

		// intensity-adjustment is intentionally NOT registered: its Spark equivalent is a two-stage
		// workflow (SparkIntensityMatching + IntensitySolver) over an N5 coefficient container, which
		// has no faithful single-action mapping from the mvrecon GUI (coefficients live in the XML).

		r.put( "icp-refine", Collections.singletonList( new Recipe(
				"match-interestpoints", true,
				new String[]{ "label", "-l" },
				new String[]{ "matchingMethod", "-m" }, // expected to be "ICP"
				new String[]{ "icpMaxError", "-ime" },
				new String[]{ "icpIterations", "-iit" },
				new String[]{ "icpUseRANSAC", "--icpUseRANSAC" }
		) ) );

		// resave's -x is the original INPUT xml (recorded as "inputXml"), not the live project,
		// which after a resave is the OUTPUT. -xo (output xml) is only recorded for formats that
		// actually write a separate xml; for Zarr v3 the metadata embeds into the -o container, so
		// "xmlOut" is absent and -xo is omitted.
		final Recipe resave = new Recipe(
				"resave", true,
				new String[]{ "n5Path", "-o" },
				new String[]{ "xmlOut", "-xo" },
				new String[]{ "storage", "-s" },
				new String[]{ "blockSize", "--blockSize" },
				new String[]{ "blockScale", "--blockScale" },
				new String[]{ "downsampling", "-ds" },
				new String[]{ "compression", "-c" },
				new String[]{ "compressionLevel", "-cl" },
				new String[]{ "useSharding", "--useSharding" }
		);
		resave.xmlParamKey = "inputXml";
		r.put( "resave", Collections.singletonList( resave ) );

		return r;
	}

	/**
	 * Render the action as zero-or-more Spark CLI command lines.
	 *
	 * @param record the action to translate
	 * @param xmlPath the project XML/URI to substitute into {@code -x}; may be null
	 * @return one or more lines; for unknown action ids a single comment line is returned
	 */
	public static List<String> render( final ActionRecord record, final String xmlPath )
	{
		if ( record == null )
			return Collections.emptyList();
		final List<Recipe> recipes = REGISTRY.get( record.getActionId() );
		if ( recipes == null )
			return Collections.singletonList( "# unknown action: " + record.getActionId() );

		final ArrayList<String> out = new ArrayList<>( recipes.size() );
		for ( final Recipe recipe : recipes )
			out.add( renderOne( recipe, record, xmlPath ) );
		return out;
	}

	private static String renderOne( final Recipe recipe, final ActionRecord r, final String xmlPath )
	{
		final StringBuilder sb = new StringBuilder();
		sb.append( recipe.script );
		if ( recipe.includeXml )
		{
			final String x = recipe.xmlParamKey != null ? r.getParams().get( recipe.xmlParamKey ) : xmlPath;
			if ( x != null && !x.isEmpty() )
				sb.append( " -x " ).append( quote( x ) );
		}

		final Map<String,String> params = r.getParams();
		for ( final Map.Entry<String,String> mapping : recipe.keyToFlag.entrySet() )
		{
			final String value = params.get( mapping.getKey() );
			if ( value == null || value.isEmpty() )
				continue;
			final String flag = mapping.getValue();
			// boolean flag (value "true"): emit just the flag; "false": omit entirely
			if ( "true".equalsIgnoreCase( value ) )
				sb.append( ' ' ).append( flag );
			else if ( "false".equalsIgnoreCase( value ) )
				continue;
			else
				sb.append( ' ' ).append( flag ).append( ' ' ).append( quote( value ) );
		}
		return sb.toString();
	}

	private static String quote( final String s )
	{
		if ( s == null )
			return "''";
		// quote if it contains shell-significant chars; otherwise leave bare
		for ( int i = 0; i < s.length(); i++ )
		{
			final char c = s.charAt( i );
			if ( c == ' ' || c == '\t' || c == '\'' || c == '"' || c == '$' || c == '\\' || c == '*' || c == '?' || c == '(' || c == ')' || c == '[' || c == ']' || c == '<' || c == '>' || c == '|' || c == '&' || c == ';' )
			{
				return "'" + s.replace( "'", "'\\''" ) + "'";
			}
		}
		return s;
	}

	/** True if the translator has a recipe for this action id. */
	public static boolean isKnown( final String actionId )
	{
		return REGISTRY.containsKey( actionId );
	}
}
